// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        int64
	Title     string
	Completed bool
	CreatedAt pgtype.Timestamp
}
